### ISSUE TITLE
Create Models 

### ISSUE THREAD

**Issue by AlexEBall** [AlexEBall/WebVR-Wall#4]

**Comment by AlexEBall** [comment]
Full Name, email, story/interview, Location (city, state, country), social media

**Comment by AlexEBall** [comment]
category

**Comment by AlexEBall** [comment]
image for profile and 360 background

**Comment by MJOAN** [comment]
model is created! named: Profile 
just have to clarify and confirm how much validation we want at this point it's not too critical because all user data we are creating ourselves. once the site is live and has more than 10+ profiles we can dig further into validation especially storyInterview string length, and location validations maybe with regex.
